/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { KnowledgeBaseContributor } from "./KnowledgeBaseContributor";
export * as factories from "./factories";
export { KnowledgeBaseContributor__factory } from "./factories/KnowledgeBaseContributor__factory";
